### ISSUE TITLE
New upstream releases, generate trailing '.' in pkg-config files thus confusing meson

### ISSUE THREAD

**Issue by xnox** [karelzak/util-linux#487]
New major upstream releases of util linux, eg. 2.28 or 2.29 generate three-part version numbers in the pkg-config files of the form `2.28.` and `2.29.` this causes relatively new build system meson to fail to parse that version string for comparison (e.g. it fails to compare `2.29. > 2.27`).

I believe this is a bug in meson, https://github.com/mesonbuild/meson/issues/1586, it should be able to do something sensiblish with trailing dots.

But I also think that for aesthetic reasons, the machine parsable version string should be consistent and unambigious in the pkg-config files. E.g. v2.28 upstream release should either generate `Version: 2.28.0` or `Version: 2.28` in the pkg-config files for the libraries.

My naive hotfix for this is:

```
--- util-linux-2.29.orig/configure.ac
+++ util-linux-2.29/configure.ac
@@ -25,7 +25,7 @@ PACKAGE_VERSION_MINOR=$(echo $PACKAGE_VE
 					      | awk -F- '{print $1}')
 
 PACKAGE_VERSION_RELEASE=$(echo $PACKAGE_VERSION | awk -F. '{print $3}' \
-						| sed 's/.*@<:@^@<:@:digit:@:>@@:>@.*/0/')
+						| sed 's/.*@<:@^@<:@:digit:@:>@@:>@.*/0/;s/^$/0/')
 
```

Which enforces a zero as the micro version number, if the .tarball-version is only a two-part number.

Please consider harmonising generated Version strings in the pkg-config files.

**Comment by rudimeier** [comment]
AFAIR this should be fixed already in the current version v2.30.

See commit 85004b14 the ones before.

**Comment by xnox** [comment]
@rudimeier That commit doesn't seem to fix it for me. As the only code path changed there, is from git, not from tarball. And the configure.ac is the one that parses the version string into three components and then sets version, e.g.

https://github.com/karelzak/util-linux/blob/master/configure.ac#L45

```
dnl libmount version
LIBMOUNT_VERSION="$PACKAGE_VERSION_MAJOR.$PACKAGE_VERSION_MINOR.$PACKAGE_VERSION_RELEASE"
LIBMOUNT_LT_MAJOR=1
LIBMOUNT_LT_MINOR=1
LIBMOUNT_LT_MICRO=0
LIBMOUNT_VERSION_INFO=`expr $LIBMOUNT_LT_MAJOR + $LIBMOUNT_LT_MINOR`:$LIBMOUNT_LT_MICRO:$LIBMOUNT_LT_MINO
```
And here the `$PACKAGE_VERSION_RELEASE` is empty, resulting in trailing `.` in the pkg-config file.

This is from analysis only. I'll try to generate a new 2.30 tarball and use non-git version derivation and will double check the resultant pkg-config files.

**Comment by rudimeier** [comment]
@xnox  mean all these  5 commit's 

    git log   170a8e4..85004b1
