### ISSUE TITLE
[2.34 and 2.35-rc2] de.po hardlink(1) mistranslation of "Saved"

### ISSUE THREAD

**Issue by mandree** [karelzak/util-linux#936]
https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/po/de.po#n9852 is mistranslated,

#: misc-utils/hardlink.c:136
msgid "Saved:        "
msgstr "**Gespeichert:**     "

msgstr should instead be **"Gespart: "** with proper amount of spaces

**Comment by mariobl** [comment]
I've just uploaded a fixed version of de.po to the TP robot.

@karelzak, translator comments for the following two Gettext messages would be really helpful:

#: misc-utils/hardlink.c:135
msgid "Would save:   "
msgstr ""

#: misc-utils/hardlink.c:136
msgid "Saved:        "
msgstr ""

**Comment by karelzak** [comment]
Seems already fixed by update from TP. Thanks!

**Comment by mandree** [comment]
Karel, the translator comments that @mariobl has requested are still pending, no? So not fully fixed...

**Comment by karelzak** [comment]
> Karel, the translator comments that @mariobl has requested are still pending, no? So not fully  fixed...

What do you want in the comment, note about the extra spaces?

**Comment by mariobl** [comment]
> > Karel, the translator comments that @mariobl has requested are still pending, no? So not fully  fixed...
> 
> What do you want in the comment, note about the extra spaces?

I like to have a comment about the meaning of "saved". Usually, it means that a file has been saved, but here it means it in sense of "save money". And of course, a hint about the count of spaces would also be helpful.
